import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HolyLoader from "holy-loader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Uniworld Aircraft",
  description: "Generated by Beinus",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HolyLoader
          color="linear-gradient(to right, #002B80, #D72528)"
          speed={250}
          easing="linear"
          showSpinner
        />
        {children}
      </body>
    </html>
  );
}
