import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import HolyLoader from "holy-loader";
import { Toaster } from "@/lib/components/ui/toaster"
import { SidebarProvider, SidebarTrigger } from "@/lib/components/ui/sidebar";
import { AppSidebar } from "@/lib/components/app-sidebar";
import { ThemeProvider } from "@/lib/components/theme-provider";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Uniworld Aircraft",
  description: "Generated by Beinus",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <HolyLoader
          color="linear-gradient(to right, #002B80, #D72528)"
          speed={250}
          easing="linear"
          showSpinner
        />
        <SidebarProvider defaultOpen={false}>
        <AppSidebar />
          <main className="w-full">
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
        </ThemeProvider>

        <Toaster />
      </body>
    </html>
  );
}
